spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: tanzicai
    password: tanzicai
  h2:
    console:
      settings:
        trace: true
        web-allow-others: true
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    open-in-view: false
  sql:
    init:
      platform: h2
      schema-locations: classpath:db/schema/user-schema.sql
      data-locations: classpath:db/data/user-data.sql
      mode: always
